### PR TITLE
Russian locale

### PR DESCRIPTION
**Pull request by DV-13**
Not sure about translation of mod's name. Direct translation sounds like "Brush, forest" so I translated it as "Brush For Forest" (Кисть Для Леса). Seems good enough

### CODE REVIEW

**Comment by DV-13** [comment]
Might as well leave mod's name in English.

**Comment by DV-13** [comment]
Maybe it's better to leave mod's name in English, idk.

**Comment by taibenvenuti** [comment]
Thanks for the translation ;)
Yeah I'll leave mod name in English like I did for the Spanish translation.

**Comment by DaEgi01** [comment]
in that case we should do it for german too XD

**Pull request merged**
